---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/please/please --version
      register: please_test_output
    - name: please --version
      debug:
        msg: '{{ please_test_output.stdout }}'
