---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for installation...
  become: yes
  become_user: root
  stat:
    path: '{{ please_install_dir }}'
  changed_when: false
  register: please_bin

- when: not please_bin.stat.exists
  block:
    - name: download...
      become: yes
      become_user: root
      get_url:
        url: '{{ please_url }}'
        dest: /tmp/{{ please_tgz }}
        mode: 0644
        checksum: '{{ please_checksums[please_ver][please_platform] }}'
    - name: make install dir
      become: yes
      become_user: root
      file:
        path: '{{ please_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive tgz...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ please_tgz }}
        dest: '{{ please_install_dir }}'
        creates: '{{ please_install_dir }}/please'
  always:
    - name: delete tgzs...
      become: yes
      become_user: root
      file:
        path: '{{ please_tgz }}'
        state: absent
- name: link please dir
  become: yes
  become_user: root
  file:
    src: '{{ please_install_dir }}/please'
    dest: '{{ please_link_dir }}'
    state: link
- name: add please to default shell...
  become: yes
  become_user: root
  with_items:
    - f: please.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
