---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for installation in {{ please_install_dir }}
  become: yes
  become_user: root
  stat:
    path: '{{ please_install_dir }}'
  changed_when: false
  register: please_bin

- when: not please_bin.stat.exists
  block:
    - name: download...
      become: yes
      become_user: root
      get_url:
        url: '{{ please_url }}'
        dest: '{{ please_tmp_tgz }}'
        mode: 0644
        checksum: '{{ please_checksum }}'
    - name: make install dir
      become: yes
      become_user: root
      file:
        path: '{{ please_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ please_tmp_tgz }} to  {{ please_install_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ please_tmp_tgz }}'
        dest: '{{ please_install_dir }}'
        creates: '{{ please_install_subdir }}'
  always:
    - name: rm {{ please_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ please_tmp_tgz }}'
        state: absent
- name: linking {{ please_link_dir }} to {{ please_install_subdir }}
  become: yes
  become_user: root
  file:
    src: '{{ please_install_subdir }}'
    dest: '{{ please_link_dir }}'
    state: link
- name: adding please to default shell...
  become: yes
  become_user: root
  with_items:
    - f: please.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
