---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for installation in {{ please_install_dir }}
  become: true
  become_user: root
  ansible.builtin.stat:
    path: '{{ please_install_dir }}'
  changed_when: false
  register: please_bin

- name: Downloading and installing please
  when: not please_bin.stat.exists
  block:
    - name: Downloading {{ please_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ please_url }}'
        dest: '{{ please_tmp_tgz }}'
        mode: '644'
        checksum: '{{ please_checksum }}'
    - name: Mkdir {{ please_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ please_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchiving {{ please_tmp_tgz }} to {{ please_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ please_tmp_tgz }}'
        dest: '{{ please_install_dir }}'
        creates: '{{ please_install_subdir }}'
  always:
    - name: Rm -f {{ please_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ please_tmp_tgz }}'
        state: absent
- name: Linking {{ please_link_dir }} to {{ please_install_subdir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ please_install_subdir }}'
    dest: '{{ please_link_dir }}'
    state: link
- name: Adding please to default shell...
  become: true
  become_user: root
  with_items:
    - f: please.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
